---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NonNilCheck:
  Enabled: false
