---
AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NonNilCheck:
  Enabled: false
