name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: docker-build
        run: |
          DOCKER_BUILDKIT=1 docker build --progress=plain --tag pictowiz:latest .
      - run: echo Status - ${{ job.status }}
